- target: ID_contract_sol_classname
  source: ID_contract_sol_classname
  method: first
- target: ID_protection_type
  source: ID_protection_type
  method: first
- target: ID_duplicate_contract
  source: ID_duplicate_contract
  method: first
- target: ID_contract_family_base
  source: ID_contract_family_base
  method: first
- target: ID_faulty_contract
  source: ID_faulty_contract
  method: first
- target: ID_odc_fault_name_specific
  source: ID_odc_fault_name_specific
  method: first
- target: ID_mutation_instance_for_type
  source: ID_mutation_instance_for_type
  method: first
- target: ID_mutation_variant_id
  source: ID_mutation_variant_id
  method: first
- target: ID_mutation_variant_name
  source: ID_mutation_variant_name
  method: first
- target: FI_bc_specific_fault
  source: FI_bc_specific_fault
  method: first
- target: FI_odc_type_name
  source: FI_odc_type_name
  method: first
- target: FI_odc_nature_name
  source: FI_odc_nature_name
  method: first
- target: FORMAL_result
  source: FORMAL_result
  method: first
- target: FORMAL_detected
  source: FORMAL_detected
  method: first
- target: FORMAL_result_classification
  source: FORMAL_result_classification
  method: first
- target: FORMAL_result_correct
  source: FORMAL_result_correct
  method: first
- target: FORMAL_assert_failures
  source: FORMAL_assert_failures
  method: first
- target: FORMAL_loopinv_failures
  source: FORMAL_loopinv_failures
  method: first
- target: FORMAL_overflow_failures
  source: FORMAL_overflow_failures
  method: first
- target: FORMAL_contrinv_failures
  source: FORMAL_contrinv_failures
  method: first
- target: FORMAL_postcond_failures
  source: FORMAL_postcond_failures
  method: first
- target: FORMAL_modification_failures
  source: FORMAL_modification_failures
  method: first
- target: FORMAL_reentrancy_failures
  source: FORMAL_reentrancy_failures
  method: first
- target: ERROR_is_timeout
  source: ERROR_is_timeout
  method: any
- target: ERROR_is_fabric_timeout
  source: ERROR_is_fabric_timeout
  method: any
- target: ERROR_is_evm_timeout
  source: ERROR_is_evm_timeout
  method: any
- target: ERROR_is_assert
  source: ERROR_is_assert
  method: any
- target: ERROR_is_require
  source: ERROR_is_require
  method: any
- target: ERROR_is_balance
  source: ERROR_is_balance
  method: any
- target: ERROR_is_modify_nonexistent_account
  source: ERROR_is_modify_nonexistent_account
  method: any
- target: ERROR_is_create_account_permission
  source: ERROR_is_create_account_permission
  method: any
- target: ERROR_is_fabric_level
  source: ERROR_is_fabric_level
  method: any
- target: ERROR_is_evm_level
  source: ERROR_is_evm_level
  method: any
- target: ERROR_is_application_level
  source: ERROR_is_application_level
  method: any
- target: ERROR_is_platform_level
  source: ERROR_is_platform_level
  method: any
- target: TX_data_integrity_error
  source: TX_data_integrity_error
  method: any
- target: TX_reliability_error
  source: TX_reliability_error
  method: any
- target: TX_accessibility_error
  source: TX_accessibility_error
  method: any
- target: TX_execution_fullmatch
  source: TX_execution_fullmatch
  method: all
- target: TX_hidden_side_effect
  source: TX_hidden_side_effect
  method: any
- target: ENDORSE_any_error
  source: ENDORSE_any_error
  method: any
- target: TX_commit_match_error
  source: TX_commit_match_error
  method: all
- target: TX_execution_fullmatch
  source: TX_execution_fullmatch
  method: all