tx_id: 'ID_tx_id'
contract_name: 'ID_contract_filename'
contract_classname: 'ID_contract_sol_classname'
faulty_contract: 'ID_faulty_contract'
odc_fault_name: 'ID_odc_fault_name_specific'
odc_fault_variant: 'ID_mutation_instance_for_type'
blockchain_specific_fault: 'FI_bc_specific_fault'
request_type: 'ID_fabric_request_type'
function_name: 'ID_function_name'
tx_index: 'ID_contract_paramdcall_idx'
odc_type_name: 'FI_odc_type_name'
odc_nature_name: 'FI_odc_nature_name'
'cc_start_epoch_ns_peer0.org1.example.com': 'CHAINCODE_p0o1_start_epoch_ns'
'cc_start_epoch_ns_peer0.org2.example.com': 'CHAINCODE_p0o2_start_epoch_ns'
'cc_end_epoch_ns_peer0.org1.example.com': 'CHAINCODE_p0o1_end_epoch_ns'
'cc_end_epoch_ns_peer0.org2.example.com': 'CHAINCODE_p0o2_end_epoch_ns'
'evm_start_epoch_ns_peer0.org1.example.com': 'EVM_p0o1_start_epoch_ns'
'evm_start_epoch_ns_peer0.org2.example.com': 'EVM_p0o2_start_epoch_ns'
'evm_end_epoch_ns_peer0.org1.example.com': 'EVM_p0o1_end_epoch_ns'
'evm_end_epoch_ns_peer0.org2.example.com': 'EVM_p0o2_end_epoch_ns'
'duration_ns_cc_peer0.org1.example.com': 'CHAINCODE_p0o1_runtime_ns'
'duration_ns_cc_peer0.org2.example.com': 'CHAINCODE_p0o2_runtime_ns'
'duration_ns_evm_peer0.org1.example.com': 'EVM_p0o1_runtime_ns'
'duration_ns_evm_peer0.org2.example.com': 'EVM_p0o2_runtime_ns'
'refdelta_duration_ns_cc_peer0.org1.example.com': 'CHAINCODE_refdelta_p0o1_runtime_ns'
'refdelta_duration_ns_cc_peer0.org2.example.com': 'CHAINCODE_refdelta_p0o2_runtime_ns'
'refdelta_duration_ns_evm_peer0.org1.example.com': 'EVM_refdelta_p0o1_runtime_ns'
'refdelta_duration_ns_evm_peer0.org2.example.com': 'EVM_refdelta_p0o2_runtime_ns'
'endorsement_result_peer0.org1.example.com': 'ENDORSE_p0o1_callresult'
'endorsement_result_peer0.org2.example.com': 'ENDORSE_p0o2_callresult'
'proposal_response_error_peer0.org1.example.com': 'ENDORSE_p0o1_error'
'proposal_response_error_peer0.org2.example.com': 'ENDORSE_p0o2_error'
status: 'COMMIT_anypeer_failure'
'commit_error_peer0.org1.example.com': 'COMMIT_p0o1_error'
'commit_error_peer0.org2.example.com': 'COMMIT_p0o2_error'
#'commit_success_peer0.org1.example.com': 'COMMIT_p0o1_success'
#'commit_success_peer0.org2.example.com': 'COMMIT_p0o2_success'
time_create: 'TX_create_epoch_ms'
time_create_rel: 'TX_create_relative_ms'
duration_ms_total: 'TX_total_time_ms'
duration_ms_endorse: 'TX_endorses_rcv_duration_ms'
duration_ms_order_and_validate: 'TX_ordervalidate_rcv_duration_ms'
refdelta_duration_ms_total: 'TX_refdelta_total_time_ms'
refdelta_duration_ms_endorse: 'TX_refdelta_endorses_rcv_duration_ms'
refdelta_duration_ms_order_and_validate: 'TX_refdelta_ordervalidate_rcv_duration_ms'
read_set_empty: 'TX_read_set_empty'
write_set_empty: 'TX_write_set_empty'
matches_reference_tx: 'TX_execution_fullmatch'
matches_return_value: 'TX_commit_match_return_value'
matches_read_set: 'TX_commit_match_read_set'
matches_write_set: 'TX_commit_match_write_set'
matches_status: 'TX_commit_match_status'
matches_error: 'TX_commit_match_error'
FormalResult: 'FORMAL_result'
assert: 'FORMAL_assert_failures'
loopinv: 'FORMAL_loopinv_failures'
overflow: 'FORMAL_overflow_failures'
contrinv: 'FORMAL_contrinv_failures'
postcond: 'FORMAL_postcond_failures'
modification: 'FORMAL_modification_failures'
reentrancy: 'FORMAL_reentrancy_failures'

