sudo chmod 774 crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/key.pem
sudo chmod 774 crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/signcerts/User1@org1.example.com-cert.pem
sudo chmod 774 crypto-config/peerOrganizations/org1.example.com/users/User2@org1.example.com/msp/keystore/key.pem
sudo chmod 774 crypto-config/peerOrganizations/org1.example.com/users/User2@org1.example.com/msp/signcerts/User2@org1.example.com-cert.pem
sudo chmod 774 crypto-config/peerOrganizations/org1.example.com/users/User3@org1.example.com/msp/keystore/key.pem
sudo chmod 774 crypto-config/peerOrganizations/org1.example.com/users/User3@org1.example.com/msp/signcerts/User3@org1.example.com-cert.pem
sudo chmod 774 crypto-config/peerOrganizations/org2.example.com/users/User1@org2.example.com/msp/keystore/key.pem
sudo chmod 774 crypto-config/peerOrganizations/org2.example.com/users/User1@org2.example.com/msp/signcerts/User1@org2.example.com-cert.pem
sudo chmod 774 crypto-config/peerOrganizations/org2.example.com/users/User2@org2.example.com/msp/keystore/key.pem
sudo chmod 774 crypto-config/peerOrganizations/org2.example.com/users/User2@org2.example.com/msp/signcerts/User2@org2.example.com-cert.pem
sudo chmod 774 crypto-config/peerOrganizations/org2.example.com/users/User3@org2.example.com/msp/keystore/key.pem
sudo chmod 774 crypto-config/peerOrganizations/org2.example.com/users/User3@org2.example.com/msp/signcerts/User3@org2.example.com-cert.pem
sudo chmod 774 crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/key.pem
sudo chmod 774 crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/signcerts/Admin@org1.example.com-cert.pem
sudo chmod 774 crypto-config/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/keystore/key.pem
sudo chmod 774 crypto-config/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/signcerts/Admin@org2.example.com-cert.pem
sudo chmod 774 crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts/tlsca.example.com-cert.pem
sudo chmod 774 crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp/tlscacerts/tlsca.org1.example.com-cert.pem
sudo chmod 774 crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/msp/tlscacerts/tlsca.org2.example.com-cert.pem